"use client";
import {Metadata} from "next";
import Link from "next/link";
import {title} from "process";
import {useEffect} from "react";

type Props = {
  params: {productId: string};
};

// Dynamic metadata
// export const generateMetadata = ({params}: Props): Metadata => {
//   return {
//     title: `Product ${params.productId}`,
//   };
// };

// export const metadata: Metadata = {
//      title: "Create Next App",
//      description: "Generated by create next app",
//    };

export default function Blob1({params}: Props) {
  useEffect(() => {
    throwError;
  });

  const throwError = () => {
    throw new Error("Something went wrong when the button was clicked!");
  };
  return (
    <>
      <div>Product {params.productId} detail</div>
      <Link href={`/products/${params.productId}/review/5/4`}>
        Product {params.productId} Reviews
      </Link>
      <button onClick={throwError}>error</button>
    </>
  );
}
