"use client";

import "./globals.css";
import Link from "next/link";
import {usePathname} from "next/navigation";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();
  const liStyle = {
    height: "50px",
    padding: "10px",
    fontSize: "1.2rem",
    cursor: "pointer",
  };
  const navStyle = {
    height: "50px",
    backgroundColor: "skyblue",
    display: "flex",
    alignItems: "center",
    gap: "20px",
    paddingLeft: "20px",
  };

  return (
    <html lang="en">
      <head></head>
      <body >
        <ul style={navStyle}>
          <Link
            style={liStyle}
            className={
              pathName.includes("/products")
                ? "font-bold bg-[green] text-white"
                : " text-green"
            }
            href={"/products"}
          >
            Products
          </Link>
          <Link
            style={liStyle}
            className={
              pathName == "/cart"
                ? "font-bold bg-[green] text-white"
                : " text-green"
            }
            href={"/cart"}
          >
            Cart
          </Link>
          <Link
            style={liStyle}
            className={
              pathName == "/profile"
                ? "font-bold bg-[green] text-white"
                : " text-green"
            }
            href={"/profile"}
          >
            Profile
          </Link>
          <Link
            style={liStyle}
            className={
              pathName.includes("/slots")
                ? "font-bold bg-[green] text-white"
                : " text-green"
            }
            href={"/slots"}
          >
            Slots
          </Link>
          <div
            style={liStyle}
            onClick={(e) => {
              throw new Error("Error in application56789");
            }}
          >
            Throw Error
          </div>
          <Link
            style={liStyle}
            className={
              pathName.includes("/polar-products")
                ? "font-bold bg-[green] text-white"
                : " text-green"
            }
            href={"/polar-products"}
          >
            Polar Products
          </Link>
          <Link
            style={liStyle}
            className={
              pathName.includes("/usage-dashboard")
                ? "font-bold bg-[green] text-white"
                : " text-green"
            }
            href={"/usage-dashboard"}
          >
            Polar Usage Dashboard
          </Link>
          {/* <Link style={liStyle} href={''}>Review</Link> */}
        </ul>
        <div style={{padding: "20px"}}>{children}</div>
      </body>
    </html>
  );
}
